version: '3'

services:
  app:
    build: ./
    image: mean
    expose:
      - 8230
    environment:
      NODE_ENV: production
      SERVER_PORT: 8230
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/mengql_app_1
      MONGO_PORT: 27017
      USER_GRAPH_ENDPOINT: /user
      USER_AUTH_ENDPOINT: /userAuth
      USER_ENABLE_GRAPHIQL: true
      ADMIN_DEPLOY: false
      ADMIN_GRAPH_ENDPOINT: /secure
      ADMIN_AUTH_ENDPOINT: /secureAuth
      ADMIN_ENABLE_GRAPHIQL: false
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
